In [1]:
import tensorflow as tf
import numpy as np

In [4]:
# feed in pure list.
def test01():
    a = tf.placeholder(tf.float32, (2, 2))
    # w = tf.Variable(tf.ones((2,2)))
    w = tf.Variable([[1,2],[1,2]], dtype=tf.float32)
    m = tf.matmul(a, w)
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    print(sess.run(m, feed_dict={a:[[2,2],[2,2]]}))

test01()

[[ 4.  8.]
 [ 4.  8.]]


In [6]:
# return of tensor.shape is tuple, not list.
def test02():
    a = tf.ones((2,2))
    sess = tf.Session()
    out_a = sess.run(a)
    print(out_a.shape)
    assert isinstance(out_a.shape, tuple), 'wrong type'
    assert (2,2) == out_a.shape, 'the shape should be equal.'
    
test02()

(2, 2)


In [21]:
# cast a tensor.shape dimension to tf.int32 for using it in tf.tile
# or just use tf.shpae()
def test03():
    a = tf.ones((3, 4), dtype=tf.float32)
    c = tf.constant([[2,2,2,2],[3,3,3,3]], dtype=tf.float32)
    d = tf.reshape(c, [-1])
    batch_size = tf.cast(a.shape[0], tf.int32)
    e = tf.tile(d, [batch_size])
    h = tf.reshape(e, (batch_size, -1))
    h1 = tf.concat([h, a], axis=1)
    sess = tf.Session()
    print(sess.run(h1))

test03()
    

[[ 2.  2.  2.  2.  3.  3.  3.  3.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  3.  3.  3.  3.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  3.  3.  3.  3.  1.  1.  1.  1.]]


In [26]:
def test04():
    a = tf.placeholder(tf.int32, (None, 2))
#     b = tf.cast(tf.shape(a)[0], tf.int32)
    b = tf.shape(a)[0]
    sess = tf.Session()
    print(sess.run(b, feed_dict={a:[[1,1],[1,1]]}))
    
test04()

2


In [8]:
# repeat vector along a special demension.
def test05():
    fw = tf.constant([[[2,2,2,2],[3,3,2,2], [0,0,0,0]]])
    bw = tf.constant([[[4,4,4,4], [5,5,5,5], [0,0,0,0]]])
    print(fw.shape)
    b = tf.concat((fw,bw), axis=2)
    print(b.shape)
    size = tf.shape(b)[0]
    c = tf.reshape(b, [size, -1])
    d = tf.tile(c,[2,1])
    with tf.Session() as sess:
        print(sess.run(c))
        print(sess.run(d))
    
test05()

(1, 3, 4)
(1, 3, 8)
[[2 2 2 2 4 4 4 4 3 3 2 2 5 5 5 5 0 0 0 0 0 0 0 0]]
[[2 2 2 2 4 4 4 4 3 3 2 2 5 5 5 5 0 0 0 0 0 0 0 0]
 [2 2 2 2 4 4 4 4 3 3 2 2 5 5 5 5 0 0 0 0 0 0 0 0]]


In [56]:
def test06():
    a = tf.constant([[2,2],[3,3],[4,4]])
    b = tf.tile(a,[1,4])
    c = tf.reshape(b,[3,4,2])
    with tf.Session() as sess:
        print(sess.run(b))
        print(sess.run(c))
        
    
test06()

[[2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]]
[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [3 3]
  [3 3]]

 [[4 4]
  [4 4]
  [4 4]
  [4 4]]]


In [64]:
# slice -1
def test07():
    a = tf.constant([[1, 1, 1, 2, 2, 2],
             [3, 3, 3, 4, 4, 4],
             [5, 5, 5, 6, 6, 6]])
    print(a.shape)
    b = tf.slice(a, [0, 0], [2, -1])
    with tf.Session() as sess:
        print(sess.run(b))

test07()

(3, 6)
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]


In [25]:
# attention
def test08():
    a = tf.constant([[2,3],[4,5]])
    b = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
    print(a.shape)
    d = tf.expand_dims(a, 2)
    print(d.shape)
    e = tf.tile(d,[1,1,3])
    print(e.shape)
    print(b.shape)
#     c = tf.multiply(b, e)
    c = b*e
    f = tf.reduce_sum(c, axis=1)
    with tf.Session() as sess:
        print(sess.run(e))
        print(sess.run(c).shape)
        print(sess.run(c))
        print(sess.run(f))
        
test08()

(2, 2)
(2, 2, 1)
(2, 2, 3)
(2, 2, 3)
[[[2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]]]
(2, 2, 3)
[[[ 2  2  2]
  [ 6  6  6]]

 [[12 12 12]
  [20 20 20]]]
[[ 8  8  8]
 [32 32 32]]


In [4]:
def mask():
    a = tf.constant([[2,3],[4,5]])
    m = tf.cast(tf.constant([[1,0], [1,0]]), tf.bool)
    a_m = tf.boolean_mask(a, m)
    with tf.Session() as sess: 
        print(sess.run(a_m))

mask()

[2 4]


In [15]:
def shape():
    a = tf.zeros([2,2,3],tf.float32)
#     c = tf.get_variable('c', [2, 4], tf.float32, tf.zeros_initializer())
    b = tf.reshape(a, [tf.shape(a)[0], -1])
    with tf.Session() as sess:
        print(sess.run(b).shape)
        
shape()

(2, 6)


In [14]:
def scope():
    with tf.variable_scope('qa', initializer=tf.zeros_initializer()):
        tf.get_variable_scope().reuse_variables()
        a = tf.get_variable('a', [2,4], tf.float32)
        #tf.get_variable_scope().reuse == True
        with tf.Session() as sess:
            sess.run(tf.global_variables_initializer())
            print(sess.run(a))
            
scope()

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [21]:
def test09():
    a = ['i', 'will']
    v = dict([(x,y) for (y,x) in enumerate(a)])
    print(v)
    
test09()

{'i': 0, 'will': 1}


In [27]:
def test10():
    a = [x for x in xrange(10)]
    a = np.array(a)
    if isinstance(a, np.ndarray):
        print('yes')
    else:
        print('no')
    b = [1, 3, 2,5]
    print(a[b])
    
test10()

yes
[1 3 2 5]


In [10]:
def gather():
    a = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
    print(a.shape)
    e = tf.slice(a,[0,0,0],[2,3,3])
#     b = tf.constant([1])
#     c = tf.gather(a, b)
    f = tf.Variable(tf.ones([1]), dtype=tf.float32)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(f))
        
gather()

(2, 2, 3)
[ 1.]


In [4]:
def evaltf():
    
    with tf.Session() as sess:
        x = tf.Variable(tf.ones([1]),dtype=tf.float32)
        sess.run(tf.global_variables_initializer())
        y = tf.multiply(x, x)
        z = 2 * tf.convert_to_tensor(y.eval())
        op = tf.train.AdamOptimizer()
#         grad = tf.gradients(z)
        grad = op.compute_gradients(z)
        sess.run(tf.global_variables_initializer())
        print(sess.run(z))
        
evaltf()

[ 2.]


In [12]:
def reverse():
    a = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
    print(a.shape)
    b=tf.reverse(a,axis=[1])
    with tf.Session() as sess:
        print(sess.run(b))
        
reverse()

(2, 2, 3)
[[[2 2 2]
  [1 1 1]]

 [[4 4 4]
  [3 3 3]]]


In [21]:
def identity_initializer():
    def _initializer(shape, dtype=tf.float32):
        if len(shape) == 1:
            return tf.constant_op.constant(0., dtype=dtype, shape=shape)
        elif len(shape) == 2 and shape[0] == shape[1]:
            return tf.constant_op.constant(np.identity(shape[0], dtype))
        elif len(shape) == 4 and shape[2] == shape[3]:
            array = np.zeros(shape, dtype=float)
            cx, cy = shape[0]/2, shape[1]/2
            for i in range(shape[2]):
                array[cx, cy, i, i] = 1
            return tf.constant_op.constant(array, dtype=dtype)
        else:
            raise
    return _initializer
def identity():
#     a = tf.get_variable('a', [2,3], tf.float32, tf.constant(tf.eye(2, num_columns=3)))
    a = tf.get_variable('a', [2,2], tf.float32,tf.constant_initializer(np.eye))
#     a = tf.Variable(tf.eye(2, num_columns=3),tf.float32)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(a))
# identity()

In [20]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import math

from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.ops import array_ops
from tensorflow.python.ops.init_ops import Initializer

class identity_initializer(Initializer):
  """Initializer that generates tensors initialized to 0."""

  def __init__(self, dtype=dtypes.float32):
    self.dtype = dtypes.as_dtype(dtype)

  def __call__(self, shape, dtype=None, partition_info=None):
    if dtype is None:
      dtype = self.dtype
#     return array_ops.zeros(shape, dtype)
    return tf.eye(shape[0], shape[1], dtype=dtype)

  def get_config(self):
    return {"dtype": self.dtype.name}

def identity():
    tf.reset_default_graph()
#     a = tf.get_variable('a', [2,3], tf.float32, tf.constant(tf.eye(2, num_columns=3)))
    a = tf.get_variable('a', [4,5], tf.float32,identity_initializer())
#     a = tf.Variable(tf.eye(2, num_columns=3),tf.float32)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(a))
identity()

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]


In [58]:
def scope():
    tf.reset_default_graph()
    with tf.variable_scope('wu', initializer=tf.zeros_initializer()) as scope:
        a = tf.get_variable('a', [4,5],tf.float32)
#     a = tf.Variable(tf.eye(2, num_columns=3),tf.float32)
        with tf.Session() as sess:
            sess.run(tf.global_variables_initializer())
            print(sess.run(a))
scope()

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [34]:
def scope1():
    tf.reset_default_graph()
    with tf.variable_scope('foo'):
        a= tf.get_variable('a',[1])
    with tf.variable_scope('foo', reuse=True):
        b=tf.get_variable('a')
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(b))
scope1()

[-1.13249898]


In [54]:
def get_v_names():
    tf.reset_default_graph()
    with tf.variable_scope('test'):
        a = tf.Variable(tf.ones([2]),tf.float32, name='a')
        b = tf.Variable(tf.zeros([3]), dtype=tf.float32, name='b',trainable=False)
    for i in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES):#TRAINABLE
        print(i.name)   # i.name if you want just a name
#     for i in tf.trainable_variables():
#         print(i.name)
        
get_v_names()

test/a:0
test/b:0


In [67]:
def shape00():
    a = tf.ones([2,2,3], tf.float32)
    a_s = tf.shape(a)[0]
    b = tf.reshape(a,[a_s, -1])
    with tf.Session() as sess:  
        print(sess.run(b))
    
shape00()

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
