In [1]:
import tensorflow as tf

In [4]:
def test01():
    a = tf.placeholder(tf.float32, (2, 2))
    # w = tf.Variable(tf.ones((2,2)))
    w = tf.Variable([[1,2],[1,2]], dtype=tf.float32)
    m = tf.matmul(a, w)
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    print(sess.run(m, feed_dict={a:[[2,2],[2,2]]}))

test01()

[[ 4.  8.]
 [ 4.  8.]]


In [10]:
def test02():
    a = tf.ones((2,2))
    sess = tf.Session()
    out_a = sess.run(a)
    print(out_a.shape)
    assert (2,2) == out_a.shape, 'the shape should be equal.'
    
test02()

(2, 2)


In [21]:
def test03():
    a = tf.ones((3, 4), dtype=tf.float32)
    c = tf.constant([[2,2,2,2],[3,3,3,3]], dtype=tf.float32)
    d = tf.reshape(c, [-1])
    batch_size = tf.cast(a.shape[0], tf.int32)
    e = tf.tile(d, [batch_size])
    h = tf.reshape(e, (batch_size, -1))
    h1 = tf.concat([h, a], axis=1)
    sess = tf.Session()
    print(sess.run(h1))

test03()
    

[[ 2.  2.  2.  2.  3.  3.  3.  3.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  3.  3.  3.  3.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  3.  3.  3.  3.  1.  1.  1.  1.]]


In [26]:
def test04():
    a = tf.placeholder(tf.int32, (None, 2))
#     b = tf.cast(tf.shape(a)[0], tf.int32)
    b = tf.shape(a)[0]
    sess = tf.Session()
    print(sess.run(b, feed_dict={a:[[1,1],[1,1]]}))
    
test04()

2


In [47]:
def test05():
    fw = tf.constant([[[2,2,2,2],[3,3,2,2], [0,0,0,0]]])
    bw = tf.constant([[[4,4,4,4], [5,5,5,5], [0,0,0,0]]])
    print(fw.shape)
    b = tf.concat((fw,bw), axis=2)
    print(b.shape)
    size = tf.shape(b)[0]
    c = tf.reshape(b, [size, -1])
    d = tf.tile(c,[1,2])
    with tf.Session() as sess:
        print(sess.run(c))
        print(sess.run(d))
    
test05()

(1, 3, 4)
(1, 3, 8)
[[2 2 2 2 4 4 4 4 3 3 2 2 5 5 5 5 0 0 0 0 0 0 0 0]]
[[2 2 2 2 4 4 4 4 3 3 2 2 5 5 5 5 0 0 0 0 0 0 0 0 2 2 2 2 4 4 4 4 3 3 2 2 5
  5 5 5 0 0 0 0 0 0 0 0]]


In [56]:
def test06():
    a = tf.constant([[2,2],[3,3],[4,4]])
    b = tf.tile(a,[1,4])
    c = tf.reshape(b,[3,4,2])
    with tf.Session() as sess:
        print(sess.run(b))
        print(sess.run(c))
        
    
test06()

[[2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]]
[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [3 3]
  [3 3]]

 [[4 4]
  [4 4]
  [4 4]
  [4 4]]]


In [6]:
def test07():
    a = tf.constant([[1, 1, 1, 2, 2, 2],
             [3, 3, 3, 4, 4, 4],
             [5, 5, 5, 6, 6, 6]])
    print(a.shape)
    b = tf.slice(a, [0, 0], [2, 6])
    with tf.Session() as sess:
        print(sess.run(b))

test07()

(3, 6)
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]


In [25]:
def test08():
    a = tf.constant([[2,3],[4,5]])
    b = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
    print(a.shape)
    d = tf.expand_dims(a, 2)
    print(d.shape)
    e = tf.tile(d,[1,1,3])
    print(e.shape)
    print(b.shape)
#     c = tf.multiply(b, e)
    c = b*e
    f = tf.reduce_sum(c, axis=1)
    with tf.Session() as sess:
        print(sess.run(e))
        print(sess.run(c).shape)
        print(sess.run(c))
        print(sess.run(f))
        
test08()

(2, 2)
(2, 2, 1)
(2, 2, 3)
(2, 2, 3)
[[[2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]]]
(2, 2, 3)
[[[ 2  2  2]
  [ 6  6  6]]

 [[12 12 12]
  [20 20 20]]]
[[ 8  8  8]
 [32 32 32]]


In [4]:
def mask():
    a = tf.constant([[2,3],[4,5]])
    m = tf.cast(tf.constant([[1,0], [1,0]]), tf.bool)
    a_m = tf.boolean_mask(a, m)
    with tf.Session() as sess: 
        print(sess.run(a_m))

mask()

[2 4]
